# -*- coding: utf-8 -*-
"""Tugas2_C14190020_Bryan Fernando Liauwan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bxy4rXYhMXyC7T5oAYr0XrtNuMUc4qaZ
"""

from google.colab import drive 
drive.mount('/content/gdrive')

import numpy as np
import matplotlib.image as image
import matplotlib.pyplot as plt

#matrix to vector
def mat2vec(img):
  h,w,t=img.shape
  size=w*h
  hasil=np.zeros(size,dtype=float)
  index=0
  for i in img:
    for j in i:
      #diubah nilainya jd -1 dan 1
      if(j[0]==255): 
        hasil[index]=-1
      else:
        hasil[index]=1
      index+=1
  return hasil

#vector to matrix
def vec2mat(arr,w,h):
  matrix=np.zeros([h,w,4])
  iter=0
  for i in range(h):
    for j in range(w):
      if(arr[iter]==-1):
        for x in range(0,4):
          matrix[i,j,x]=255
      else:
        for x in range(0,3):
          matrix[i,j,x]=0
        matrix[i,j,3]=255
      iter+=1
  return matrix

#load image to vector -> matrix
img=image.imread("/content/gdrive/My Drive/Semester 5/5_1_2_ML/images/train/bin_image1.gif")
imgarr=mat2vec(img)
mtx=np.array(imgarr)

img=image.imread("/content/gdrive/My Drive/Semester 5/5_1_2_ML/images/train/bin_image2.gif")
imgarr=mat2vec(img)
mtx=np.vstack([mtx,imgarr])

img=image.imread("/content/gdrive/My Drive/Semester 5/5_1_2_ML/images/train/bin_image3.gif")
imgarr=mat2vec(img)
mtx=np.vstack([mtx,imgarr])

img=image.imread("/content/gdrive/My Drive/Semester 5/5_1_2_ML/images/train/bin_image4.gif")
imgarr=mat2vec(img)
mtx=np.vstack([mtx,imgarr])

img=image.imread("/content/gdrive/My Drive/Semester 5/5_1_2_ML/images/train/bin_image5.gif")
imgarr=mat2vec(img)
mtx=np.vstack([mtx,imgarr])

w=(mtx.T@mtx)/mtx.shape[0]-np.eye(mtx.shape[1])
#tranning done

fig=plt.figure(figsize=(10, 10))
r=3; c=2; counter=0

for a in range(1,4):
  path = "/content/gdrive/My Drive/Semester 5/5_1_2_ML/images/test/bin_corr" + str(a) + ".gif"
  imgcorrupted=image.imread(path)
  imgcorrupted_arr=mat2vec(imgcorrupted)

  #Iterasi
  i=0
  while 1:
    i+=1
    recovery=np.sign(w@imgcorrupted_arr)
    if((recovery==imgcorrupted_arr).all()):
      break
    else:
      imgcorrupted_arr=recovery
      #print(i)

  imgcorrupted_done=vec2mat(imgcorrupted_arr,imgcorrupted.shape[1],imgcorrupted.shape[0])

  counter+=1
  fig.add_subplot(r, c, counter)
  plt.imshow(imgcorrupted)
  plt.axis('off')
  plt.title("Gambar Terdistorsi")

  counter+=1
  fig.add_subplot(r, c, counter)
  plt.imshow(imgcorrupted_done)
  plt.axis('off')
  plt.title("Gambar Recovery")